"""The rule-prose reachability guard, red, green and blind (FM-01 + FM-24).

The guard revives a mechanism FM-23 declined, at a narrower scope, so the
tests carry that boundary as well as the failure shapes: a `README.md` naming
a development path must stay legal, because that file is FM-23's own
counterexample and is not rule prose an agent is told to follow.
"""
import json
import subprocess

import check_repo

SHIPPED = json.dumps({
    "schema": 1,
    "$comment": "probe",
    "consumer_seeds": ["shipper"],
    "seeds_comment": "probe",
    "dev_pins": [],
    "pins_comment": "probe",
    "rules": [
        {"prefix": "references/", "side": "consumer", "why": "rule prose"},
        {"prefix": "SKILL.md", "side": "consumer", "why": "entry point"},
        {"prefix": "README.md", "side": "consumer", "why": "the front door"},
        {"prefix": "adapters/", "side": "consumer", "why": "registry"},
        # No `scripts/` rule, deliberately: the real manifest has none either,
        # and the side of a script is COMPUTED from reachability. A probe that
        # declares one tests a tree this repository does not have.
    ],
})


def _repo(tmp_path, files):
    subprocess.run(["git", "init", "-q"], cwd=tmp_path, check=True)
    base = {
        "adapters/shipped.json": SHIPPED,
        "scripts/render/shipper.py": "x = 1\n",
        "scripts/build/private_tool.py": "y = 1\n",
        # The exclusion has to match SOMETHING or the guard says so, and that
        # branch is asserted below rather than left to the real tree.
        "references/generated.md": "<!-- GENERATED by `scripts/build/gen.py` -->\n"
                                   "see scripts/build/private_tool.py\n",
        "SKILL.md": "the entry point\n",
    }
    base.update(files)
    for name, content in base.items():
        p = tmp_path / name
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(content)
    subprocess.run(["git", "add", "-A"], cwd=tmp_path, check=True)
    return tmp_path


def _run(tmp_path, monkeypatch, files):
    monkeypatch.setattr(check_repo, "ROOT", _repo(tmp_path, files))
    monkeypatch.setattr(check_repo, "RULE_SCRIPT_WAIVERS", {}, raising=False)
    return check_repo.check_rule_script_reach()


def test_a_rule_naming_a_shipped_script_passes(tmp_path, monkeypatch):
    assert _run(tmp_path, monkeypatch, {
        "references/design-rules.md": "run scripts/render/shipper.py to draw it\n"
    }) == []


def test_a_rule_naming_a_development_script_fails(tmp_path, monkeypatch):
    out = _run(tmp_path, monkeypatch, {
        "references/design-rules.md": "one\ntwo\nrun scripts/build/private_tool.py\n"
    })
    assert len(out) == 1
    assert "references/design-rules.md:3" in out[0]
    assert "does not carry" in out[0]


def test_a_readme_naming_a_development_script_is_untouched(tmp_path, monkeypatch):
    """FM-23's counterexample. A README attributing a development-side file is
    correct prose, and the scope — not a grammar test — is what protects it."""
    assert _run(tmp_path, monkeypatch, {
        "README.md": "scripts/build/private_tool.py, in the development repository\n"
    }) == []


def test_a_generated_index_is_excluded_by_its_own_banner(tmp_path, monkeypatch):
    """`references/generated.md` in the base tree cites a development path and
    must not be reported: its generator's banner takes it out of scope."""
    out = _run(tmp_path, monkeypatch, {
        "references/design-rules.md": "clean\n"})
    assert out == []


def test_a_generator_that_drops_its_banner_is_reported(tmp_path, monkeypatch):
    out = _run(tmp_path, monkeypatch, {
        "references/generated.md": "see scripts/build/private_tool.py\n"})
    assert any("citations have not been checked" in x or "does not carry" in x
               for x in out)
    assert any("generated-file exclusion matched nothing" in x for x in out)


def test_no_rule_file_in_scope_is_not_a_pass(tmp_path, monkeypatch):
    """FM-24. A scan with nothing in scope printed a clean line in the draft.

    Reached by putting the rule prose on the DEVELOPMENT side rather than by
    deleting it: `SKILL.md` seeds the reachability computation, so deleting it
    tests the OTHER blind branch, which has its own test below.
    """
    dev_rules = SHIPPED.replace('"references/", "side": "consumer"',
                                '"references/", "side": "dev"')
    dev_rules = dev_rules.replace('"SKILL.md", "side": "consumer"',
                                  '"SKILL.md", "side": "dev"')
    out = _run(tmp_path, monkeypatch, {"adapters/shipped.json": dev_rules})
    assert any("no consumer-side, hand-written rule file" in x for x in out)


def test_an_uncomputable_boundary_is_not_a_pass(tmp_path, monkeypatch):
    """The second blind branch, and a different sentence from the first."""
    monkeypatch.setattr(check_repo, "ROOT", _repo(tmp_path, {}))
    monkeypatch.setattr(check_repo, "RULE_SCRIPT_WAIVERS", {}, raising=False)
    (tmp_path / "SKILL.md").unlink()
    subprocess.run(["git", "add", "-A"], cwd=tmp_path, check=True)
    out = check_repo.check_rule_script_reach()
    assert len(out) == 1
    assert "boundary could not be computed" in out[0]
    assert "not a scan that passed" in out[0]


def test_a_waiver_excuses_and_a_dead_waiver_is_reported(tmp_path, monkeypatch):
    tree = {"references/design-rules.md": "run scripts/build/private_tool.py\n"}
    monkeypatch.setattr(check_repo, "ROOT", _repo(tmp_path, tree))
    key = ("references/design-rules.md", "scripts/build/private_tool.py")
    monkeypatch.setattr(check_repo, "RULE_SCRIPT_WAIVERS",
                        {key: "probe reason"}, raising=False)
    assert check_repo.check_rule_script_reach() == []
    monkeypatch.setattr(check_repo, "RULE_SCRIPT_WAIVERS",
                        {("references/nowhere.md", "scripts/build/x.py"): "r"},
                        raising=False)
    out = check_repo.check_rule_script_reach()
    assert any("outlived its reason" in x for x in out)
