"""The rule-prose reachability guard, red, green and blind (FM-01 + FM-24).

The guard revives a mechanism FM-23 declined, at a narrower scope, so the
tests carry that boundary as well as the failure shapes: a `README.md` naming
a development path must stay legal, because that file is FM-23's own
counterexample and is not rule prose an agent is told to follow.
"""
import json
import subprocess

import check_repo

SHIPPED = json.dumps({
    "schema": 1,
    "$comment": "probe",
    "consumer_seeds": ["shipper"],
    "seeds_comment": "probe",
    "dev_pins": [],
    "pins_comment": "probe",
    "rules": [
        {"prefix": "references/", "side": "consumer", "why": "rule prose"},
        {"prefix": "SKILL.md", "side": "consumer", "why": "entry point"},
        {"prefix": "AGENTS.md", "side": "consumer", "why": "entry point"},
        {"prefix": "prompts/", "side": "consumer", "why": "the prompt tier"},
        {"prefix": "README.md", "side": "consumer", "why": "the front door"},
        {"prefix": "adapters/", "side": "consumer", "why": "registry"},
        # No `scripts/` rule, deliberately: the real manifest has none either,
        # and the side of a script is COMPUTED from reachability. A probe that
        # declares one tests a tree this repository does not have.
    ],
})


def _repo(tmp_path, files):
    subprocess.run(["git", "init", "-q"], cwd=tmp_path, check=True)
    base = {
        "adapters/shipped.json": SHIPPED,
        "scripts/render/shipper.py": "x = 1\n",
        "scripts/build/private_tool.py": "y = 1\n",
        # The exclusion has to match SOMETHING or the guard says so, and that
        # branch is asserted below rather than left to the real tree.
        "references/generated.md": "<!-- GENERATED by `scripts/build/gen.py` -->\n"
                                   "see scripts/build/private_tool.py\n",
        # A consumer-side citation, so the probe trees do not trip the
        # "SCRIPT_PATH_RE matched nothing" branch — which is about the
        # pattern going stale, not about a tree with little in it.
        "SKILL.md": "the entry point; run scripts/render/shipper.py\n",
    }
    base.update(files)
    for name, content in base.items():
        p = tmp_path / name
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(content)
    subprocess.run(["git", "add", "-A"], cwd=tmp_path, check=True)
    return tmp_path


def _run(tmp_path, monkeypatch, files):
    monkeypatch.setattr(check_repo, "ROOT", _repo(tmp_path, files))
    monkeypatch.setattr(check_repo, "RULE_SCRIPT_WAIVERS", {}, raising=False)
    return check_repo.check_rule_script_reach()


def test_a_rule_naming_a_shipped_script_passes(tmp_path, monkeypatch):
    assert _run(tmp_path, monkeypatch, {
        "references/design-rules.md": "run scripts/render/shipper.py to draw it\n"
    }) == []


def test_a_rule_naming_a_development_script_fails(tmp_path, monkeypatch):
    out = _run(tmp_path, monkeypatch, {
        "references/design-rules.md": "one\ntwo\nrun scripts/build/private_tool.py\n"
    })
    assert len(out) == 1
    assert "references/design-rules.md:3" in out[0]
    assert "does not carry" in out[0]


def test_a_readme_naming_a_development_script_is_untouched(tmp_path, monkeypatch):
    """FM-23's counterexample. A README attributing a development-side file is
    correct prose, and the scope — not a grammar test — is what protects it."""
    assert _run(tmp_path, monkeypatch, {
        "README.md": "scripts/build/private_tool.py, in the development repository\n"
    }) == []


def test_a_generated_index_is_excluded_by_its_own_banner(tmp_path, monkeypatch):
    """`references/generated.md` in the base tree cites a development path and
    must not be reported: its generator's banner takes it out of scope."""
    out = _run(tmp_path, monkeypatch, {
        "references/design-rules.md": "clean\n"})
    assert out == []


def test_a_generator_that_drops_its_banner_is_reported(tmp_path, monkeypatch):
    out = _run(tmp_path, monkeypatch, {
        "references/generated.md": "see scripts/build/private_tool.py\n"})
    assert any("does not carry" in x for x in out), out
    assert any("generated-file exclusion matched nothing" in x for x in out)


def test_no_rule_file_in_scope_is_not_a_pass(tmp_path, monkeypatch):
    """FM-24. A scan with nothing in scope printed a clean line in the draft.

    Reached by putting the rule prose on the DEVELOPMENT side rather than by
    deleting it: `SKILL.md` seeds the reachability computation, so deleting it
    tests the OTHER blind branch, which has its own test below.
    """
    dev_rules = SHIPPED.replace('"references/", "side": "consumer"',
                                '"references/", "side": "dev"')
    dev_rules = dev_rules.replace('"SKILL.md", "side": "consumer"',
                                  '"SKILL.md", "side": "dev"')
    out = _run(tmp_path, monkeypatch, {"adapters/shipped.json": dev_rules})
    assert any("no consumer-side, hand-written rule file" in x for x in out)


def test_an_uncomputable_boundary_is_not_a_pass(tmp_path, monkeypatch):
    """The second blind branch, and a different sentence from the first."""
    monkeypatch.setattr(check_repo, "ROOT", _repo(tmp_path, {}))
    monkeypatch.setattr(check_repo, "RULE_SCRIPT_WAIVERS", {}, raising=False)
    (tmp_path / "SKILL.md").unlink()
    subprocess.run(["git", "add", "-A"], cwd=tmp_path, check=True)
    out = check_repo.check_rule_script_reach()
    assert len(out) == 1
    assert "boundary could not be computed" in out[0]
    assert "not a scan that passed" in out[0]


def test_a_waiver_excuses_and_a_dead_waiver_is_reported(tmp_path, monkeypatch):
    tree = {"references/design-rules.md": "run scripts/build/private_tool.py\n"}
    monkeypatch.setattr(check_repo, "ROOT", _repo(tmp_path, tree))
    key = ("references/design-rules.md", "scripts/build/private_tool.py")
    monkeypatch.setattr(check_repo, "RULE_SCRIPT_WAIVERS",
                        {key: "probe reason"}, raising=False)
    assert check_repo.check_rule_script_reach() == []
    monkeypatch.setattr(check_repo, "RULE_SCRIPT_WAIVERS",
                        {("references/nowhere.md", "scripts/build/x.py"): "r"},
                        raising=False)
    out = check_repo.check_rule_script_reach()
    assert any("outlived its reason" in x for x in out)


# --- the real tree, not a probe ------------------------------------------
# Convention 15: a check that has never fired on a real artifact is not a
# check. These run against this repository, and they pin RELATIONSHIPS rather
# than counts — convention 13, because "15 files scanned" goes stale the next
# time someone writes a reference file, and a test that cries wolf on a correct
# change is a test people delete.

def test_the_scope_partitions_the_real_tree():
    """Every consumer-side rule file is either scanned or excluded — never
    silently neither, which is how a file leaves a guard's reach unnoticed."""
    import pathlib

    import check_rule_coverage
    import repo_files
    import shipped
    root = pathlib.Path(check_repo.ROOT)
    names, problem = repo_files.tracked_files(root=root, what="scope probe")
    assert not problem
    consumer_set = shipped.consumer_scripts(root)
    family = [n for n in names if n.endswith(".md")
              and n.startswith(check_rule_coverage.RULE_FILE_PREFIXES)]
    consumer = [n for n in family
                if shipped.side_of(n, root, consumer_set) == "consumer"]
    excluded = [n for n in consumer
                if check_repo.GENERATED_BANNER.search(
                    "\n".join((root / n).read_text(encoding="utf-8")
                              .splitlines()[:10]))]
    scanned = [n for n in consumer if n not in excluded]
    assert consumer, "no consumer-side rule file — the guard has nothing to read"
    assert scanned, "everything in scope was excluded; the guard is blind"
    assert excluded, ("the banner exclusion matched nothing, so the guard's "
                      "false-positive rate rests on an exclusion that is not "
                      "working")
    assert len(scanned) + len(excluded) == len(consumer)


def test_the_exclusion_matches_generated_files_and_only_those():
    """Named rather than counted, so a fourth generated index fails HERE with
    its name in the message instead of shifting a number nobody reads.
    If that happens: confirm the new file is generated, then add it below."""
    import pathlib

    import check_rule_coverage
    import repo_files
    import shipped
    root = pathlib.Path(check_repo.ROOT)
    names, _ = repo_files.tracked_files(root=root, what="scope probe")
    consumer_set = shipped.consumer_scripts(root)
    excluded = {n for n in names if n.endswith(".md")
                and n.startswith(check_rule_coverage.RULE_FILE_PREFIXES)
                and shipped.side_of(n, root, consumer_set) == "consumer"
                and check_repo.GENERATED_BANNER.search(
                    "\n".join((root / n).read_text(encoding="utf-8")
                              .splitlines()[:10]))}
    assert excluded == {"references/build-card.md",
                        "references/eval-inventory.md",
                        "references/page-contracts.md"}


def test_the_guard_is_green_on_this_repository():
    assert check_repo.check_rule_script_reach() == []


def test_the_guard_is_registered():
    """A guard with no CHECKS entry does not run, however green its own tests.
    Found by mutation: deleting both new rows left the whole suite passing."""
    assert any(fn is check_repo.check_rule_script_reach
               for _name, fn in check_repo.CHECKS)


def test_every_prefix_in_the_family_is_actually_scanned(tmp_path, monkeypatch):
    """Found by mutation: dropping `AGENTS.md` and `prompts/` from the family
    survived every test, because the probe trees only ever used `references/`
    and `SKILL.md`. `prompts/lumi-style-core.md` is the file whose readers have
    NO tools at all — the population this guard exists for.

    `SKILL.md` is excluded and `test_skill_md_cannot_violate_this_guard` below
    says why: naming a script there is what makes it ship.
    """
    # SPELLED OUT, not read from the constant under test. The first version
    # iterated `RULE_FILE_PREFIXES`, so shrinking the constant shrank the loop
    # and the mutation survived a second time — a self-referential assertion
    # proves nothing about the thing it reads.
    import check_rule_coverage
    assert set(check_rule_coverage.RULE_FILE_PREFIXES) == {
        "references/", "SKILL.md", "AGENTS.md", "prompts/", "CLAUDE.md"}, (
        "the rule-file family changed; decide what the new member means for "
        "reachability before updating this list")
    for prefix in ("references/", "AGENTS.md", "prompts/"):
        name = prefix + "probe.md" if prefix.endswith("/") else prefix
        out = _run(tmp_path, monkeypatch,
                   {name: "run scripts/build/private_tool.py\n"})
        assert any(f"{name}:1" in x for x in out), (
            f"{prefix} is in the rule-file family and a citation in it was not "
            f"reported — the prefix is declared and not scanned")


def test_skill_md_cannot_violate_this_guard(tmp_path, monkeypatch):
    """And that is correct, not a hole. `shipped.consumer_scripts` SEEDS the
    consumer set from SKILL.md's own invocations, so naming a script there is
    the act that makes it ship. The file stays in scope because the family is
    one fact and because a `prompts/` or `AGENTS.md` citation is a real
    violation; SKILL.md's immunity is a property of the boundary, not an
    exemption anyone wrote."""
    out = _run(tmp_path, monkeypatch, {
        "SKILL.md": "the entry point; run scripts/render/shipper.py\n"
                    "run scripts/build/private_tool.py\n"})
    assert out == [], out


def test_the_banner_window_is_the_first_ten_lines(tmp_path, monkeypatch):
    """Found by mutation: widening the window to the whole file survived.
    Over-exclusion is SILENT — `excluded` merely increments — so the window is
    pinned rather than left to the exclusion set's contents."""
    body = "\n".join(["filler"] * 12)
    out = _run(tmp_path, monkeypatch, {
        "references/late-banner.md":
            body + "\n<!-- GENERATED by `scripts/build/gen.py` -->\n"
                   "see scripts/build/private_tool.py\n"})
    assert any("late-banner.md" in x and "does not carry" in x for x in out), (
        "a banner below the tenth line took a file out of scope; the window is "
        "what keeps a stale generator loud")


def test_two_citations_in_one_file_are_both_reported(tmp_path, monkeypatch):
    """Found by mutation: reporting only the first survived — no probe tree had
    a rule file with two."""
    out = _run(tmp_path, monkeypatch, {
        "references/design-rules.md":
            "run scripts/build/private_tool.py\n"
            "and also scripts/build/other_tool.py\n",
        "scripts/build/other_tool.py": "z = 1\n"})
    assert len(out) == 2, out
