"""Redrawing the table is not re-recording the measurement.

A board is a photograph of one session, and every history row carries which
version of the rules its agents were measured against. `report --record` on an
old run stamps those rows with TODAY's version — claiming the agents read rules
that did not exist when they ran, which is the misattribution 0.1.605 exists to
describe. So when the WORDING changes and the measurement does not, there was
nothing to do but wait for the next round.

`--redraw` is the narrow answer: the table, the failure list and the header
render from the run directory that is still on disk, and `history.json` is
never opened.
"""
import json

import pytest
import run_conformance

_REAL_HISTORY = run_conformance.ROOT / "conformance" / "history.json"
VERSION = "0.1.999"


@pytest.fixture(autouse=True)
def real_history_untouched():
    before = _REAL_HISTORY.read_bytes()
    yield
    assert _REAL_HISTORY.read_bytes() == before


def _tree(tmp_path, monkeypatch):
    (tmp_path / "SKILL.md").write_text(
        f'---\nmetadata:\n  version: "{VERSION}"\n---\n', encoding="utf-8")
    (tmp_path / "CHANGELOG.md").write_text(
        f"## {VERSION} — a release\n\nbody\n", encoding="utf-8")
    (tmp_path / "adapters").mkdir()
    (tmp_path / "adapters" / "platforms.json").write_text(json.dumps(
        {"platforms": [{"id": "a1", "name": "Agent One", "capability": "prompt"}]}),
        encoding="utf-8")
    tasks = tmp_path / "conformance" / "tasks"
    tasks.mkdir(parents=True)
    (tasks / "T1.json").write_text(json.dumps(
        {"id": "T1", "prompt": "p", "min_capability": "prompt",
         "score": ["prose"], "deliverable": "*.md"}), encoding="utf-8")
    board = tmp_path / "conformance" / "CONFORMANCE.md"
    board.write_text(
        "<!-- generated by run_conformance.py report --record -->\n"
        "# LUMI style conformance · skill 0.0.1\n\nold table\n"
        "<!-- end generated -->\n\n"
        "## Earlier runs, in their own words\n\nHand-written, left as written.\n",
        encoding="utf-8")
    history = tmp_path / "conformance" / "history.json"
    history.write_text(json.dumps(
        [{"agent": "a1", "date": "2026-01-01", "run_dir": "x",
          "scores_sha256": "d" * 64, "skill_version": "0.0.1",
          "instrument_version": "0.0.1",
          "tasks": {"T1": "pass"}}]), encoding="utf-8")
    run = tmp_path / "run1"
    run.mkdir()
    (run / "scores.json").write_text(json.dumps({
        "a1/T1": {"verdict": "pass",
                  "task_hash": run_conformance.task_fingerprint(json.loads(
                      (tasks / "T1.json").read_text(encoding="utf-8")))}}),
        encoding="utf-8")
    for attr, value in (("ROOT", tmp_path),
                        ("REGISTRY", tmp_path / "adapters" / "platforms.json"),
                        ("TASKS", tasks),
                        ("RESULTS", tmp_path / "conformance" / "results")):
        monkeypatch.setattr(run_conformance, attr, value)
    return board, history, run


def test_redraw_rewrites_the_table_and_not_the_history(tmp_path, monkeypatch,
                                                       capsys):
    board, history, run = _tree(tmp_path, monkeypatch)
    before = history.read_text(encoding="utf-8")
    assert run_conformance.main(["report", "--redraw", "--run", str(run)]) == 0
    text = board.read_text(encoding="utf-8")
    assert "old table" not in text
    assert "| Agent One" in text
    assert history.read_text(encoding="utf-8") == before, (
        "redraw touched history.json; a row's version stamp is the one thing "
        "it must not move")


def test_redraw_leaves_the_hand_written_history_below_the_marker(
        tmp_path, monkeypatch, capsys):
    board, _, run = _tree(tmp_path, monkeypatch)
    run_conformance.main(["report", "--redraw", "--run", str(run)])
    text = board.read_text(encoding="utf-8")
    assert "Earlier runs, in their own words" in text
    assert "Hand-written, left as written." in text


def test_redraw_says_when_there_was_nothing_to_do(tmp_path, monkeypatch, capsys):
    board, _, run = _tree(tmp_path, monkeypatch)
    run_conformance.main(["report", "--redraw", "--run", str(run)])
    capsys.readouterr()
    assert run_conformance.main(["report", "--redraw", "--run", str(run)]) == 0
    assert "already reads this way" in capsys.readouterr().out


def test_redraw_does_not_rescore(tmp_path, monkeypatch, capsys):
    """It renders the recorded verdicts; it never re-runs a checker.

    Re-scoring would be re-measuring — today's instruments over yesterday's
    artifact — which is a different claim from redrawing how a verdict is
    written.
    """
    board, _, run = _tree(tmp_path, monkeypatch)
    scores = (run / "scores.json").read_text(encoding="utf-8")
    run_conformance.main(["report", "--redraw", "--run", str(run)])
    assert (run / "scores.json").read_text(encoding="utf-8") == scores


def test_redraw_refuses_a_board_with_no_generated_region(tmp_path, monkeypatch,
                                                         capsys):
    """`write_board` reports rather than raises, and the caller must read it.

    A board whose markers are gone returns a `FAIL ` string. The first version
    printed that, then diffed the file against itself, then printed
    "the board already reads this way" as the LAST line and returned 0 — so a
    wrapper reading the tail or the exit status saw success over a refusal.
    """
    board, _, run = _tree(tmp_path, monkeypatch)
    board.write_text("# LUMI style conformance · skill 0.0.1\n\nno markers\n",
                     encoding="utf-8")
    assert run_conformance.main(["report", "--redraw", "--run", str(run)]) == 1
    out = capsys.readouterr().out
    assert "carries no generated region" in out
    assert "already reads this way" not in out


def test_redraw_refuses_a_run_the_board_is_not_about(tmp_path, monkeypatch,
                                                     capsys):
    """Redraw rewrites how a measurement is worded, never which one it is.

    Nothing compared the two, so `--redraw --run <another round>` rewrote the
    table with a different session's verdicts, left the history rows describing
    the old one, and reported success — with "history.json untouched" as the
    reassurance.
    """
    board, _, run = _tree(tmp_path, monkeypatch)
    run_conformance.main(["report", "--redraw", "--run", str(run)])
    capsys.readouterr()
    other = tmp_path / "run2"
    other.mkdir()
    (other / "scores.json").write_text((run / "scores.json").read_text(
        encoding="utf-8"), encoding="utf-8")
    before = board.read_text(encoding="utf-8")
    assert run_conformance.main(["report", "--redraw", "--run", str(other)]) == 1
    assert "never which measurement it is" in capsys.readouterr().out
    assert board.read_text(encoding="utf-8") == before


def test_redraw_and_record_together_is_refused(tmp_path, monkeypatch, capsys):
    """`--record` was silently dropped: redraw returned before it ran."""
    _, history, run = _tree(tmp_path, monkeypatch)
    before = history.read_text(encoding="utf-8")
    assert run_conformance.main(
        ["report", "--redraw", "--record", "--run", str(run)]) == 1
    assert "Pick one" in capsys.readouterr().out
    assert history.read_text(encoding="utf-8") == before


def test_the_marker_names_the_command_not_a_flag(tmp_path, monkeypatch):
    """A board written by `--redraw` was stamped as written by `--record`.

    This is the release where the difference is load-bearing: redraw's whole
    argument is that it deliberately does not touch history, and the board's
    own first line said it had been recorded.
    """
    board, _, run = _tree(tmp_path, monkeypatch)
    run_conformance.main(["report", "--redraw", "--run", str(run)])
    text = board.read_text(encoding="utf-8")
    assert run_conformance.BOARD_OPEN in text
    assert "--record" not in text.splitlines()[0]


def test_a_board_carrying_the_old_marker_is_still_readable(tmp_path,
                                                           monkeypatch):
    """Every board on disk was written with the previous form.

    Refusing them would have meant regenerating a file to make it readable,
    which is the trade a marker change must not impose.
    """
    board, _, run = _tree(tmp_path, monkeypatch)
    board.write_text(board.read_text(encoding="utf-8").replace(
        run_conformance.BOARD_OPEN, run_conformance.BOARD_OPEN_LEGACY, 1),
        encoding="utf-8")
    assert run_conformance.main(["report", "--redraw", "--run", str(run)]) == 0
    text = board.read_text(encoding="utf-8")
    assert "| Agent One" in text
    assert "Hand-written, left as written." in text
