#!/usr/bin/env python3
"""Generate LUMIVATE's brand marks.

    python3 scripts/build_brand.py            # write
    python3 scripts/build_brand.py --check    # verify current (CI)

The globe is LUMIVATE's icon. It is generated from the same projection and the
same topology as the figures, rather than drawn, so the mark on a cover and the
figure inside it are the same object at two sizes — which is the whole reason a
company mark built from a component is worth having.

WHAT AN ICON DROPS. Everything that needs room to be read: cities, bloc fills,
bloc labels, trade lanes, signals, the terminator. At 96px a name is three
pixels tall and a lane is a scratch. What survives is the sphere, the
graticule, the coastline and the axis — and the axis is what makes a 96px disc
read as a planet rather than a circle with texture on it.

Two sizes, because one does not serve both ends:

    globe-mark.svg        coastline, graticule and axis, for 64px and up
    globe-mark-small.svg  coastline and axis, no graticule, for 16-48px

The small one is not the large one scaled down. Below about 48px a 15-degree
graticule falls closer together than the pixels and turns to moire, so it is
left out rather than shrunk — while the coastline, being a filled silhouette,
survives being small and is the only thing that says planet at 16px.

These files are LOCKED. See assets/brand/LOCKED.json.
"""
from __future__ import annotations

import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))

import globe_svg                                                   # noqa: E402

OUT_DIR = ROOT / "assets" / "brand" / "lumivate"

# Centred on 20E so Europe, Africa and western Asia fill the disc: a mark wants
# land in it, and an ocean-centred globe reads as an empty circle at icon size.
VIEW = (20.0, 18.0, 0.0, 100.0, 100.0, 100.0)

# SELF-CONTAINED, AND MONOCHROME. A figure's palette is built to recede behind
# data — the land is --acc-2, a wash — and a mark rendered in it disappears at
# 64px. A mark also has to survive being dropped into a page that has never
# heard of tokens/region-palette.css, so it carries its own styles inline.
#
# One ink at three strengths, taken from --nw (#212621), because a logo has to
# work in one colour: on a letterhead, in a favicon, stamped, faxed. The values
# are literals here on purpose — a var() in a mark is a var() that resolves to
# nothing on somebody else's page.
MARK_STYLE = (
    "<style>"
    ".lumivate-mark .gl-plate{fill:none}"
    ".lumivate-mark .gl-graticule{fill:none;stroke:#212621;stroke-opacity:.28;"
    "stroke-width:1.1}"
    ".lumivate-mark .gl-land{fill:#212621;fill-opacity:.86;stroke:none}"
    ".lumivate-mark .gl-axis{stroke:#212621;stroke-width:3;stroke-linecap:round}"
    ".lumivate-mark .gl-limb{fill:none;stroke:#212621;stroke-opacity:.55;"
    "stroke-width:2}"
    "</style>")

NOTE = ("<!-- LUMIVATE brand mark. GENERATED by scripts/build_brand.py and "
        "LOCKED: see assets/brand/LOCKED.json. Do not edit, and do not change "
        "what it is generated from without the brand owner's sign-off. -->")


def _strip(svg, classes):
    """Drop whole elements by class. An icon is what is left."""
    for cls in classes:
        svg = re.sub(rf'<(path|circle|line|text|g)\b[^>]*class="[^"]*\b{cls}\b'
                     rf'[^"]*"[^>]*/>\s*', "", svg)
        svg = re.sub(rf'<(path|circle|line|text|g)\b[^>]*class="[^"]*\b{cls}\b'
                     rf'[^"]*"[^>]*>.*?</\1>\s*', "", svg, flags=re.S)
    return svg


def build(small=False):
    svg = globe_svg.render(VIEW, night=None)
    svg = _strip(svg, ["gl-night", "gl-node", "gl-equator", "gl-tropic",
                       "gl-axis-ref"])
    if small:
        # The SMALL mark drops the GRATICULE, not the land. Dropping the land
        # was the obvious cut and it was the wrong one: it left a plain disc
        # with a line through it, which reads as a prohibition sign and not as
        # a planet. Below 48px a 15-degree graticule is moire — the lines fall
        # closer together than the pixels — while a filled continent is a
        # silhouette, and a silhouette is exactly what survives being small.
        svg = _strip(svg, ["gl-graticule"])
    svg = svg.replace('class="gl"', 'class="gl lumivate-mark"', 1)
    # The limb: the sphere's own edge. The figure gets it from the plate fill,
    # which a mark has no use for — a logo with a filled disc behind it cannot
    # sit on a dark background — so the mark draws the circle instead.
    lon0, lat0, t, R, cx, cy = VIEW
    limb = (f'<circle class="gl-limb" cx="{cx:g}" cy="{cy:g}" r="{R:g}"/>')
    svg = svg.replace('<g class="gl-earth"', MARK_STYLE + limb + '<g class="gl-earth"', 1)
    svg = svg.replace('aria-label="LUMI globe, field of marks"',
                      'aria-label="LUMIVATE"', 1)
    svg = re.sub(r"<!-- generated by scripts/globe_svg\.py[^>]*-->", NOTE, svg, count=1)
    return svg.rstrip() + "\n"


TARGETS = {"globe-mark.svg": False, "globe-mark-small.svg": True}


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)

    failed = 0
    for name, small in TARGETS.items():
        path = OUT_DIR / name
        built = build(small)
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if args.check:
            if current != built:
                print(f"FAIL  {path.relative_to(ROOT)} is stale or missing; "
                      f"re-run without --check")
                failed = 1
            else:
                print(f"ok    {path.relative_to(ROOT)} is current")
            continue
        OUT_DIR.mkdir(parents=True, exist_ok=True)
        path.write_text(built, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}  ({len(built):,} bytes)")
    return failed


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
