#!/usr/bin/env python3
"""The region map runtime as one inline <script> a deliverable can carry.

The map's mirror of embed_globe.py, and dramatically lighter for a reason worth
stating: the map runtime touches no geometry — scripts/regionmap_svg.py bakes
the projected world into the markup and the runtime updates state only — so
this block inlines the REGISTRY (names, a few KB) and NOT the 68 KB topology
the globe must carry to re-project every frame. Hit testing is the browser's
own pointer events on real <path> elements; there is nothing here to compute.

    python3 scripts/embed_regionmap.py                          # the block, to stdout
    python3 scripts/embed_regionmap.py --states '{"europe":{"state":"live","value":63}}'
    python3 scripts/embed_regionmap.py --check                  # CI

Per-element states: an element may name its own data with
`data-regionmap-states="#some-json"`, pointing at an adjacent
<script type="application/json"> — no fetch, so it works over file://. Without
it the element takes the block's --states.

Standard library only.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
# The strip/guard machinery is embed_globe's; a second copy would drift.
from embed_globe import (   # noqa: E402
    strip_module_syntax, dedupe_top_consts, IMPORT_RE,
)

ROOT = pathlib.Path(__file__).resolve().parent.parent
RUNTIME = ROOT / "assets" / "regionmap" / "regionmap.js"
REGIONS = ROOT / "assets" / "vectors" / "regions.json"


def build(states=None):
    src = RUNTIME.read_text(encoding="utf-8")
    src, conflicts = dedupe_top_consts("regionmap.js", strip_module_syntax(src), {})
    if conflicts:
        raise SystemExit("FAIL  " + "\n      ".join(conflicts))
    reg = json.loads(REGIONS.read_text(encoding="utf-8"))

    host = {"regions": {}}
    for rid, v in (states or {}).items():
        host["regions"][rid] = v if isinstance(v, dict) else {"state": v}

    return f"""<script>
/* LUMI region map runtime — GENERATED by scripts/embed_regionmap.py. Do not
 * edit here.
 *
 * Inlined rather than imported: a deliverable is opened over file://, where
 * the browser refuses ES modules as cross-origin. It mutates the markup
 * scripts/regionmap_svg.py emitted and never creates any, so with JavaScript
 * off the reader still gets exactly that frame.
 */
(function () {{
  var REGISTRY = {json.dumps(reg, separators=(',', ':'), ensure_ascii=False)};
  var HOSTDATA = {json.dumps(host, separators=(',', ':'), ensure_ascii=False)};
{src.strip()}

  function statesFor(el) {{
    var sel = el.dataset.regionmapStates;
    if (!sel) return HOSTDATA;
    var node = document.querySelector(sel);
    if (!node) return HOSTDATA;
    try {{ return {{ regions: JSON.parse(node.textContent).regions
                            || JSON.parse(node.textContent) }}; }}
    catch (e) {{ return HOSTDATA; }}
  }}

  function boot() {{
    var figures = document.querySelectorAll('[data-regionmap]');
    for (var i = 0; i < figures.length; i += 1) {{
      createRegionMap(figures[i], {{
        registry: REGISTRY,
        hostData: statesFor(figures[i]),
        interactive: figures[i].dataset.regionmap !== 'static',
      }});
    }}
  }}
  if (document.readyState === 'loading') {{
    document.addEventListener('DOMContentLoaded', boot);
  }} else {{
    boot();
  }}
}})();
</script>"""


def check():
    """The failures that would not be visible until a reader opened the file."""
    errors = []
    try:
        block = build(states={"europe": {"state": "live", "value": 63}})
    except SystemExit as exc:
        print(exc)
        return 1
    body = block.split("<script>", 1)[1].rsplit("</script>", 1)[0]
    if IMPORT_RE.search(body):
        errors.append("an unresolved import survived the strip")
    for needle, why in (("export ", "a surviving export is a SyntaxError inline"),
                        ("await import(", "a dynamic import fetches, which file:// refuses"),
                        ("fetch(", "a deliverable must not fetch")):
        if needle in body:
            errors.append(why)
    if "createRegionMap" not in body:
        errors.append("the runtime lost its entry point")
    for err in errors:
        print(f"FAIL  {err}")
    if not errors:
        print(f"ok    region map runtime inlines cleanly "
              f"({len(block) // 1024} KB, registry only — no topology)")
    return 1 if errors else 0


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--states", metavar="JSON", default=None)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)
    if args.check:
        return check()
    states = json.loads(args.states) if args.states else None
    print(build(states=states))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
